version: "3.8"
services:
  db:
    image: postgres:16-alpine
    container_name: json-voucher-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: voucherdb
      POSTGRES_USER: voucher
      POSTGRES_PASSWORD: voucher
    volumes:
      - voucher_data:/var/lib/postgresql/data

volumes:
  voucher_data: